### ISSUE TITLE
GPL compliance

### ISSUE THREAD

**Issue by henrik242** [szym/barnacle#5]
Since Barnacle was released as GPL in June 2010, several new versions have been released.  The source code for the new releases seems to be missing, and are thus not in compliance with the GPL.

**Comment by szym** [comment]
True, I have not updated the source code for a while. You could have just e-mailed me for the recent code, but since you raised this as issue of "compliance", let me clarify.

You need to understand that this is not how GPL works. As the sole author and copyright holder, I am the only one who can enforce the licence and thus GPL binds everyone who uses the source code but me. I can release the software under other terms if I choose. See: http://www.gnu.org/licenses/gpl-faq.html#ReleaseUnderGPLAndNF

**Comment by henrik242** [comment]
Ah! Thanks for the clarification, I wasn't aware of this.
